version: '3.5'
services:
  qndxx:
    build: .
    ports:
      - "6106:5000"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - $PWD/img/:/home/dxx/img
      - $PWD/log/:/home/dxx/DxxLog
    tty: true
    networks:
      - net

networks: 
  net: 
    driver: bridge
